&lt;!-- wrapper --&gt;
&lt;div class="wrapper"&gt;
  &lt;!-- gallery wrap --&gt;
  &lt;div class="gallery clearfix"&gt;
    &lt;!-- gallery item 1 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image1.jpg" class="gallery_img" alt="image alt 1" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 2 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image2.jpg" class="gallery_img" alt="image alt 2" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 3 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image3.jpg" class="gallery_img" alt="image alt 3" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 4 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image4.jpg" class="gallery_img" alt="image alt 4" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 5 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image5.jpg" class="gallery_img" alt="image alt 5" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 6 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image6.jpg" class="gallery_img" alt="image alt 6" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 7 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image7.jpg" class="gallery_img" alt="image alt 7" /&gt;
    &lt;/div&gt;
    &lt;!-- gallery item 8 --&gt;
    &lt;div class="gallery_item"&gt;
      &lt;img src="img/image8.jpg" class="gallery_img" alt="image alt 8" /&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;

&lt;!-- gallery control wrapper --&gt;
&lt;div class="gallery_controls clearfix"&gt;
  &lt;!-- left control --&gt;
  &lt;div class="gallery_controls-prev"&gt;
    &lt;i class="fa fa-chevron-left fa-2x"&gt;&lt;/i&gt;
  &lt;/div&gt;
  &lt;!-- right control --&gt;
  &lt;div class="gallery_controls-next"&gt;
    &lt;i class="fa fa-chevron-right fa-2x"&gt;&lt;/i&gt;
  &lt;/div&gt;
&lt;/div&gt;