&lt;!-- battleship board --&gt;
&lt;div id="board"&gt;
  &lt;!-- battleship message display --&gt;
  &lt;h1 id="messageArea"&gt;&lt;/h1&gt;
  &lt;!-- battleship user inputs --&gt;
  &lt;form&gt;
    &lt;div id="input-group"&gt;
      &lt;input type="text" id="guessInput" placeholder="A0" autofocus class="form-control"&gt;
      &lt;input type="button" id="fireButton" value="Fire!" class="btn btn-danger"&gt;
    &lt;/div&gt;
  &lt;/form&gt;
  &lt;!-- battleship table --&gt;
  &lt;table&gt;
    &lt;!-- battleship row 0 --&gt;
    &lt;tr&gt;
      &lt;td id="00"&gt;&lt;/td&gt;&lt;td id="01"&gt;&lt;/td&gt;&lt;td id="02"&gt;&lt;/td&gt;&lt;td id="03"&gt;&lt;/td&gt;&lt;td id="04"&gt;&lt;/td&gt;&lt;td id="05"&gt;&lt;/td&gt;&lt;td id="06"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 1 --&gt;
    &lt;tr&gt;
      &lt;td id="10"&gt;&lt;/td&gt;&lt;td id="11"&gt;&lt;/td&gt;&lt;td id="12"&gt;&lt;/td&gt;&lt;td id="13"&gt;&lt;/td&gt;&lt;td id="14"&gt;&lt;/td&gt;&lt;td id="15"&gt;&lt;/td&gt;&lt;td id="16"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 2 --&gt;
    &lt;tr&gt;
      &lt;td id="20"&gt;&lt;/td&gt;&lt;td id="21"&gt;&lt;/td&gt;&lt;td id="22"&gt;&lt;/td&gt;&lt;td id="23"&gt;&lt;/td&gt;&lt;td id="24"&gt;&lt;/td&gt;&lt;td id="25"&gt;&lt;/td&gt;&lt;td id="26"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 3 --&gt;
    &lt;tr&gt;
      &lt;td id="30"&gt;&lt;/td&gt;&lt;td id="31"&gt;&lt;/td&gt;&lt;td id="32"&gt;&lt;/td&gt;&lt;td id="33"&gt;&lt;/td&gt;&lt;td id="34"&gt;&lt;/td&gt;&lt;td id="35"&gt;&lt;/td&gt;&lt;td id="36"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 4 --&gt;
    &lt;tr&gt;
      &lt;td id="40"&gt;&lt;/td&gt;&lt;td id="41"&gt;&lt;/td&gt;&lt;td id="42"&gt;&lt;/td&gt;&lt;td id="43"&gt;&lt;/td&gt;&lt;td id="44"&gt;&lt;/td&gt;&lt;td id="45"&gt;&lt;/td&gt;&lt;td id="46"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 5 --&gt;
    &lt;tr&gt;
      &lt;td id="50"&gt;&lt;/td&gt;&lt;td id="51"&gt;&lt;/td&gt;&lt;td id="52"&gt;&lt;/td&gt;&lt;td id="53"&gt;&lt;/td&gt;&lt;td id="54"&gt;&lt;/td&gt;&lt;td id="55"&gt;&lt;/td&gt;&lt;td id="56"&gt;&lt;/td&gt;
    &lt;/tr&gt;
    &lt;!-- battleship row 6 --&gt;
    &lt;tr&gt;
      &lt;td id="60"&gt;&lt;/td&gt;&lt;td id="61"&gt;&lt;/td&gt;&lt;td id="62"&gt;&lt;/td&gt;&lt;td id="63"&gt;&lt;/td&gt;&lt;td id="64"&gt;&lt;/td&gt;&lt;td id="65"&gt;&lt;/td&gt;&lt;td id="66"&gt;&lt;/td&gt;
    &lt;/tr&gt;
  &lt;/table&gt;
&lt;/div&gt;